#!/bin/bash

BOTNAME=`whoami`
ICON=":strawberry:"
MESSAGE=""
CHANNEL="#nochannel"
WEBHOOK=""

FROM=`hostname`

while getopts 'f:n:m:c:' OPTIONS
do
    case ${OPTIONS} in
        f)
            FROM=${OPTARG};;
        n)
            BOTNAME=${OPTARG};;
        m)
            MESSAGE=${OPTARG};;
        c)
            CHANNEL=${OPTARG};;
        *)
            echo "Invalid argument."
            exit 1;;
    esac
done

MESSAGE="\n*From*: $FROM\n*Message*: $MESSAGE"

# Try read message from pipe
test -p /dev/stdin && MESSAGE=$MESSAGE"\n"'```'`< /dev/stdin`'```'

curl -X POST \
--data-urlencode "payload={'text':'<!channel> $MESSAGE','channel':'$CHANNEL','username':'$BOTNAME','icon_emoji':'$ICON'}" \
$WEBHOOK
